//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuChi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyThuChiEntities : DbContext
    {
        public QuanLyThuChiEntities()
            : base("name=QuanLyThuChiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MucChi> MucChis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThongTinChiTien> ThongTinChiTiens { get; set; }
        public virtual DbSet<ThongTinThuTien> ThongTinThuTiens { get; set; }
        public virtual DbSet<Userrr> Userrrs { get; set; }
        public virtual DbSet<ThuChiii> ThuChiiis { get; set; }
    }
}
