//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuChi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinChiTien
    {
        public int STT { get; set; }
        public string LyDo { get; set; }
        public string TenMuc { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SoTienChi { get; set; }
    }
}
