//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuChi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ThuChiii
    {
        public int ID { get; set; }

        [Display(Name="Lý do")]
        public string LyDo { get; set; }
        [Required(ErrorMessage ="{0} chưa được nhập !")]

        [Display(Name = "Tên mục")]
        public string TenMuc { get; set; }
        [Required(ErrorMessage = "{0} chưa được nhập !")]

        [Display(Name = "Ngày")]
        public Nullable<System.DateTime> Date { get; set; }
        [Required(ErrorMessage = "{0} chưa được nhập !")]

        [Display(Name = "Số tiền")]
        public Nullable<int> SoTien { get; set; }
        [Required(ErrorMessage = "{0} chưa được nhập !")]

        [Display(Name = "Thu/Chi")]
        public string ThuChi { get; set; }
    }
}
