//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuChi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Userrr
    {

        public int ID { get; set; }

        [Display(Name="Tên bạn")]
        public string Name { get; set; }
        [Required(ErrorMessage ="{0} chưa nhập nè !")]

        [Display(Name = "Ngày sinh")]
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required(ErrorMessage = "{0} chưa nhập nè !")]


        [Display(Name = "CMND")]
        public string Cmnd { get; set; }
        [Required(ErrorMessage = "{0} chưa nhập nè !")]


        [Display(Name = "Call")]
        public string SDT { get; set; }
        [Required(ErrorMessage = "{0} chưa nhập nè !")]


        [Display(Name = "Địa chỉ")]
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "{0} chưa nhập nè !")]


        [Display(Name = "Ghi chú")]
        public string GhiChu { get; set; }
        [Required(ErrorMessage = "{0} chưa nhập nè !")]


        [Display(Name = "Tài khoản")]
        public string TaiKhoan { get; set; }
        [Required(ErrorMessage = "{0} chưa nhập nè !")]


        [Display(Name = "Mật khẩu")]
        public string MatKhau { get; set; }
    }
}
